apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/preranabl/sockshop-chart.git'
    targetRevision: main         # branch of GitOps repo
    path: "."                   # look inside /apps for child apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd            # root apps usually live in argocd ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

