apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sock-shop-fe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sockshop
  source:
    repoURL: 'https://github.com/preranabl/sockshop-chart.git'
    targetRevision: main        
    path: '.'          
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
