apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sockshop-fe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sockshop
  source:
    repoURL: 'https://github.com/preranabl/sockshop-chart.git'
    targetRevision: main        
    path: '.'          
    helm:
      values: |
        replicaCount: 2
        appName: fe-app
        image:
          repository: weaveworksdemos/front-end
          tag: "sha-52dee65"
          pullPolicy: IfNotPresent

        service:
          type: ClusterIP
          port: 80
          targetPort: 8079

        ingress:
          enabled: true
          className: 'ingress-external'
          host: sockshop.local
          path: /

        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        env:
          CATALOGUE_DOMAIN: "catalogue.sockshop.svc.cluster.local"
          CARTS_DOMAIN: "carts.sockshop.svc.cluster.local"
          ORDERS_DOMAIN: "orders.sockshop.svc.cluster.local"
          USER_DOMAIN: "user.sockshop.svc.cluster.local"
          PAYMENT_DOMAIN: "payment-app.sockshop.svc.cluster.local"
          NODE_ENV: "production"
          PORT: "8079"

  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
